version: "3"
services:
  stock-service:
    container_name: stock-service
    image: mysql:latest
    environment:
      MYSQL_DATABASE: stock-service-db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3302:3306
    volumes:
      - mysql:/var/lib/product
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 30s
      timeout: 30s
      retries: 3
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
        "--default-authentication-plugin=mysql_native_password"
      ]
volumes:
  mysql: